version: '3.1'

services:
  node:
    container_name: nodetube
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env.settings:/app/.env.settings
      - ./.env.private:/app/.env.private
      - ./recordings:/app/recordings
      - ./hls:/app/hls
      - ./upload:/app/upload
      - ./uploads:/app/uploads
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://nodetube-mongo:27017/nodetube
    depends_on:
      - redis
      - mongo
    command: npm start
    networks:
      - nodetube-network

  mongo:
    container_name: nodetube-mongo
    image: mongo:4.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "27011:27017"
    networks:
      - nodetube-network

  redis:
    container_name: nodetube-redis
    image: redis
    networks:
      - nodetube-network

  nginx:
    container_name: nodetube-nginx-rtmp
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf.template
      - ./hls:/app/hls
      - ./recordings:/app/recordings
      - ./upload:/app/upload
      - ./uploads:/app/uploads
    depends_on:
      - node
    networks:
      - nodetube-network

networks:
  nodetube-network:
    driver: bridge
