FROM node:10-alpine3.11 as builder
RUN apk add --no-cache tar git g++ make python
COPY package* .env* copySettingsAndPrivateFiles.js /app/
WORKDIR /app
RUN npm i --production
RUN node ./copySettingsAndPrivateFiles.js && \
    rm -rf /app/node_modules/ffprobe-static/bin/darwin && \
    rm -rf /app/node_modules/ffprobe-static/bin/win32 && \
    rm -rf /app/node_modules/ffprobe-static/bin/linux/ia32 && \
    rm -rf /app/node_modules/webp-converter/bin/libwebp_win64 && \
    rm -rf /app/node_modules/webp-converter/bin/libwebp_osx && \
    strip /app/node_modules/ngrok/bin/ngrok

FROM node:10-alpine3.11 AS Nodetube_image
EXPOSE 3000 8080
COPY --from=builder /app/ /app/
COPY app* Procfile routes.js .npmrc LICENSE.MD /app/
COPY caching /app/caching/
COPY config /app/config/
COPY controllers /app/controllers/
COPY keys /app/keys/
COPY lib /app/lib/
COPY media /app/media/
COPY middlewares /app/middlewares/
COPY models /app/models/
COPY public /app/public/
COPY scripts /app/scripts/
COPY views /app/views/
RUN ln -s /app/node_modules/ffprobe-static/bin/linux/x64/ffprobe /app/node_modules/@ffmpeg-installer/linux-x64/ffmpeg /usr/local/bin/
WORKDIR /app
CMD ["npm", "start"]
